kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: hello-backend-prod
spec:
  replicas: 2
  template:
    metadata:
      name: backend
      labels:
        app: hello-backend
        role: backend
        env: production
    spec:
      containers:
      - name: backend
        image: gcr.io/cd-in-kubernetes/hello-back:1.0
        ports:
        - name: backend
          containerPort: 8080
