kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: hello-frontend-prod
spec:
  replicas:
  template:
    metadata:
      name: frontend
      labels:
        app: hello-frontend
        role: frontend
        env: production
    spec:
      containers:
      - name: frontend
        image: gcr.io/cd-in-kubernetes/hello-front:1.0
        ports:
        - name: frontend
          containerPort: 80
